### ISSUE TITLE
Cost to Implement: add new form field

### ISSUE THREAD

**Issue by hannahkarl** [FriendlyDesignCo/ROI-calculator#24]
Add a new entry at the end, before the final total. This is added to the other values to get the total.

Miscellaneous Costs
Enter other costs you associate with this project, such as equipment donation, travel, or stipends/wages for interns.
(right aligned box to enter – populated initially at $0)

**Comment by mccahan** [comment]
On the ROI page? Where should we put this field?

**Comment by hannahkarl** [comment]
On the Cost to Implement page. Should be:

Project Planning
Project Management
Workforce Supervision
Miscellaneous Costs

All added to equal Total Implementation Cost
