### ISSUE TITLE
ROI module calculations shouldn't show any decimal places

### ISSUE THREAD

**Issue by hannahkarl** [FriendlyDesignCo/ROI-calculator#3]
![screen shot 2015-06-03 at 3 27 05 pm](https://cloud.githubusercontent.com/assets/11408606/7969466/029c3144-0a05-11e5-9eb2-57c37a32734f.png)
...just 972%

**Comment by mccahan** [comment]
e484dff53fc84c3efd8efbd162914426dc750f9d
