### ISSUE TITLE
Add space around operators between form fields

### ISSUE THREAD

**Issue by hannahkarl** [FriendlyDesignCo/ROI-calculator#30]
![screen shot 2015-06-25 at 3 05 23 pm](https://cloud.githubusercontent.com/assets/11408606/8363235/a7297b7a-1b4b-11e5-9599-64b92455679b.png)
this amount of space throughout is ideal.

**Comment by mccahan** [comment]
I did quite a bit on these to try and get some spacing in there throughout, including rebuilding some of the structure of the way the fields work on smaller screens to try and maintain readability for the smaller screens. There's not much more I can do on this front, the complexity is already increasing significantly to try and level out these fields.
