### ISSUE TITLE
Spacing of ROI total area

### ISSUE THREAD

**Issue by hannahkarl** [FriendlyDesignCo/ROI-calculator#35]
![screen shot 2015-06-25 at 3 48 28 pm](https://cloud.githubusercontent.com/assets/11408606/8364126/b4446efe-1b51-11e5-9f15-a5d00d35dda6.png)

2x current padding top and bottom of the green box.

**Comment by mccahan** [comment]
Fixed in 7b854c03c1cbff4a1466633991b28e5a235c5e4d
